### ISSUE TITLE
Не запускается

### ISSUE THREAD

**Issue by GeTechG** [kr0tyara/toonator#1]
Всё ок по инструкции, но на моменте с `haxe openfl test html5 -debug` у меня выходит сообщение:
```
Error: Library swf is not installed
Error: Could not process asset libraries (swf)
```

**Comment by kr0tyara** [comment]
Написано же белым по чёрному: не установлена библиотека swf.
```
haxelib install swf
```

**Comment by GeTechG** [comment]
> 
> 
> Написано же белым по чёрному: не установлена библиотека swf.
> 
> ```
> haxelib install swf
> ```

Я уже понял, но почему бы это в инструкции не написать.
